### ISSUE TITLE
Create Start Panel

### ISSUE THREAD

**Issue by kyleisryan** [arv124/CatCatch#1]
The initial JPanel for the home screen needs to be designed. It will contain a start button to launch the game, a high scores button to link them to the high scores pane, and a credits panel. It also needs a title "Cat Catch".

**Comment by kalabanana** [comment]
***The main panel will have a line of text that says "Credit to ...."
***The main panel will contain three panels: main panel, game panel, and high score panel. After "Start Game" button is clicked, the window will refresh to the next panel, which is game panel. If the player loses the game, the window will then refresh to the high score panel.

**Comment by kalabanana** [comment]
Screen size: 400*300
